[window]
padding = { x = 24, y = 24 }
dynamic_padding = true
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 1.0
title = "Alacritty"
dynamic_title = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[colors]
primary = { background = '#282c34', foreground = '#abb2bf' }
normal = { black = '#282c34', red = '#e06c75', green = '#98c379', yellow = '#d19a66', blue = '#61afef', magenta = '#c678dd', cyan = '#56b6c2', white = '#abb2bf' }
bright = { black = '#5c6370', red = '#e06c75', green = '#98c379', yellow = '#d19a66', blue = '#61afef', magenta = '#c678dd', cyan = '#56b6c2', white = '#ffffff' }
