# Configuration for Alacritty

window:
  padding:
    x: 16
    y: 16
  dynamic_padding: true
  decorations: buttonless
  startup_mode: Windowed
  opacity: 1.0
  title: Alacritty
  dynamic_title: false

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 14
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic

schemes:
  onedark: &onedark
    primary:
      background: '#282c34'
      foreground: '#abb2bf'
    normal:
      black: '#282c34'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#d19a66'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#abb2bf'
    bright:
      black: '#5c6370'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#d19a66'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#ffffff'

colors: *onedark

# support for macos keybinds
key_bindings:
  - { key: Key2, mods: Alt, chars: '€' }
  - { key: Key3, mods: Alt, chars: '#' }

live_config_reload: true
