# support for macos keyboard shortcuts

key_bindings:
  - { key: Key0, mods: Alt, chars: 'º' }
  - { key: Key1, mods: Alt, chars: '¡' }
  - { key: Key2, mods: Alt, chars: '€' }
  - { key: Key3, mods: Alt, chars: '#' }
  - { key: Key4, mods: Alt, chars: '¢' }
  - { key: Key5, mods: Alt, chars: '∞' }
  - { key: Key6, mods: Alt, chars: '§' }
  - { key: Key7, mods: Alt, chars: '¶' }
  - { key: Key8, mods: Alt, chars: '•' }
  - { key: Key9, mods: Alt, chars: 'ª' }

window:
  # spread additional padding evenly around terminal content
  dynamic_padding: true

  decorations: buttonless

  opacity: 1.0

  startup_mode: Maximized

  title: Alacritty
  dynamic_title: false

  padding:
    x: 16
    y: 16

scrolling:
  history: 10000

font:
  size: 14
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

schemes:
  onedark: &onedark
    primary:
      background: '#282c34'
      foreground: '#abb2bf'
    normal:
      black: '#282c34'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#d19a66'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#abb2bf'
    bright:
      black: '#5c6370'
      red: '#e06c75'
      green: '#98c379'
      yellow: '#d19a66'
      blue: '#61afef'
      magenta: '#c678dd'
      cyan: '#56b6c2'
      white: '#ffffff'

colors: *onedark

live_config_reload: true
